### ISSUE TITLE
[api] Make api more declarative

### ISSUE THREAD

**Issue by Nevraeka** [RevillWeb/rebel-repeater#1]
Instead of using attribute for element container, use this pattern and extend `HTMLTemplateElement` instead of `HTMLElement`

``` html
<ul>
  <!-- start rebel repeater code -->
  <rebel-repeater content="[{ 'firstName' : 'Samwise', ''lastName' : 'Gamgee'}]">
    <li>${firstName} ${lastName}</li> 
  </rebel-repeater>
  <!-- end rebel repeater code -->
</ul>
```

**Comment by Nevraeka** [comment]
i think is should be called `<dom-repeater>` or `<template-repeater>`

**Comment by RevillWeb** [comment]
@Nevraeka I totally agree about the first point, means they would have direct access to the parent so they can easily add classes etc. I'm open to changing the name but was thinking of keeping some branding to entice people to try out RebelJS ;-) (when finished).

**Comment by RevillWeb** [comment]
Removed the element attribute and RblRepeater extends the HTMLTemplateElement instead.
